apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
  labels:
    app: shophub
data:
  # Django settings
  DEBUG: "False"
  ALLOWED_HOSTS: "backend-service,localhost,127.0.0.1"
  
  # Database settings
  DB_NAME: "ecommerce_db"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  
  # API URL for frontend
  NEXT_PUBLIC_API_URL: "http://backend-service:8000/api/v1"

