apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
  labels:
    app: shophub
type: Opaque
stringData:
  # Django secret key (à changer en production)
  SECRET_KEY: "django-insecure-kubernetes-secret-key-change-in-production"
  
  # Database password
  DB_PASSWORD: "postgres"
  POSTGRES_PASSWORD: "postgres"
  
  # Superuser credentials
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@example.com"
  DJANGO_SUPERUSER_PASSWORD: "admin123"

