apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
  labels:
    app: shophub
type: Opaque
stringData:
  # Django secret key (générée de manière sécurisée)
  SECRET_KEY: "fv@#+t_7+$0m+i!0t^bgz3o7=67599+p%zzt4y*m!n#0-w+f^2"
  
  # Database password
  DB_PASSWORD: "postgres"
  POSTGRES_PASSWORD: "postgres"
  
  # Superuser credentials
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@example.com"
  DJANGO_SUPERUSER_PASSWORD: "admin123"

